import Head from 'next/head'
import Image from "next/image";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Linkedin-2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Linkedin-Clone-2.0-Nextjs-Tailwind</p>
    </div>
  );
}
